// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW6eGmpMfv9wAU121lNe9Q0eaqDSvuf2E',
    appId: '1:453796402336:web:d608001ffad464a32c65c5',
    messagingSenderId: '453796402336',
    projectId: 'connectx-massenger',
    authDomain: 'connectx-massenger.firebaseapp.com',
    storageBucket: 'connectx-massenger.firebasestorage.app',
    measurementId: 'G-FCSYERCQGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAS6XC8Aky6Ei32mbPSxVmkGkAMyKWDgY',
    appId: '1:453796402336:android:c16f08025493927e2c65c5',
    messagingSenderId: '453796402336',
    projectId: 'connectx-massenger',
    storageBucket: 'connectx-massenger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7RWzVMEYoJTj6-FBcRV3uqtfM3vStK1U',
    appId: '1:453796402336:ios:03dc6e91c6e58cbd2c65c5',
    messagingSenderId: '453796402336',
    projectId: 'connectx-massenger',
    storageBucket: 'connectx-massenger.firebasestorage.app',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7RWzVMEYoJTj6-FBcRV3uqtfM3vStK1U',
    appId: '1:453796402336:ios:03dc6e91c6e58cbd2c65c5',
    messagingSenderId: '453796402336',
    projectId: 'connectx-massenger',
    storageBucket: 'connectx-massenger.firebasestorage.app',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW6eGmpMfv9wAU121lNe9Q0eaqDSvuf2E',
    appId: '1:453796402336:web:bc9b8c18c8c11a842c65c5',
    messagingSenderId: '453796402336',
    projectId: 'connectx-massenger',
    authDomain: 'connectx-massenger.firebaseapp.com',
    storageBucket: 'connectx-massenger.firebasestorage.app',
    measurementId: 'G-Z99Z760PF7',
  );

}